
function Convert_T2C(TimeScalingFactor,...
                      CruiseName, ...
                      Latitude, ...
                      Longitude, ...
                      PenetrationRecord, ...
                      HeatPulseRecord, ...
                      EndRecord, ...
                      StationName, ...
                      Penetration, ...
                      SensorsToUse, ...
                      AllSensorsTemp, ...
                      AllRecords, ...
                      WaterSensorTemp)

% CRUISE    Cruise name in the pen-file header, not used.
% LAT       Latitude, pen-file header.
% LON       Longitude, pen-file header.
% N_PEN     Time index penetration, pen-file header.
% N_PULSE   Time index heat-pulse, pen-file header.
% N_REC     Time index last record of the pen.
% SNUM      Station number, pen-file header.
% PNUM      Penetration number, pen-file header.
% INCL      Vector with indices of the used sensors      
% T         Matrix with reduced temperature data. One column per sensor. Reduction method specified by W_CAL      
 
% t         Time vector corresponding to T
% TILT      Sensor tilt, pen-file header. %% NOT NEEDED %%   
% Tc        Temperature readings for calibration, pen-file header   %% NOT NEEDED %%   
% Tw        Water sensor reading.
% WDEP      Water depth, pressure sensor. %% NOT NEEDED %% 

CRUISE = CruiseName;
LAT    = Latitude;
LON    = Longitude;
N_PEN  = TimeScalingFactor*PenetrationRecord;
N_PULS = TimeScalingFactor*HeatPulseRecord;
N_REC  = TimeScalingFactor*EndRecord;
SNUM   = str2double(StationName);
PNUM   = str2double(Penetration);
INCL   = SensorsToUse;
T      = AllSensorsTemp;

t      = TimeScalingFactor*AllRecords;

Tw     = WaterSensorTemp;

save('t2c_kd.mat', ...
'CRUISE',...
'LAT',...
'LON',...
'N_PEN',...
'N_PULS',...
'N_REC',...
'SNUM',...
'PNUM',...
'INCL',...
'T',...
't',...
'Tw');
